
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-lvm-topolvm-io-v1alpha1-lvmcluster
  failurePolicy: Fail
  name: mlvmcluster.kb.io
  rules:
  - apiGroups:
    - lvm.topolvm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lvmclusters
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-lvm-topolvm-io-v1alpha1-lvmcluster
  failurePolicy: Fail
  name: vlvmcluster.kb.io
  rules:
  - apiGroups:
    - lvm.topolvm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lvmclusters
  sideEffects: None
