apiVersion: v1
kind: Service
metadata:
  name: topolvm-node-metrics
  labels:
    app.kubernetes.io/compose: metrics
spec:
  selector:
    app.lvm.openshift.io: topolvm-node
  ports:
    - name: topolvm-metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
