---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topolvm-metrics
rules:
 - apiGroups:
   - ""
   resources:
    - services
    - endpoints
    - pods
   verbs:
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topolvm-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: topolvm-metrics
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
