name: weekly-image-build

# Runs every Monday at 23:00 UTC
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 1"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    if: >
      github.repository == 'red-hat-storage/lvm-operator' &&
      github.ref == 'refs/heads/main'
    steps:
      - name: invoke-operator-build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: manual-operator-build-push
          repo: red-hat-storage/lvm-operator
          inputs: '{ "branch": "main" }'
